services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123!
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
      - ./Scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_strong_password123! -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - SA_PASSWORD=Your_strong_password123!
    volumes:
      - ./Scripts:/scripts:ro
    command: >
      /bin/sh -c "
        echo 'SQL Server is ready. Starting database initialization...';
        echo 'Creating Auth database...';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_strong_password123! -C -Q 'IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = ''NiceDentistAuthDb'') CREATE DATABASE NiceDentistAuthDb;';
        echo 'Creating Manager database...';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_strong_password123! -C -Q 'IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = ''NiceDentistManagerDb'') CREATE DATABASE NiceDentistManagerDb;';
        echo 'Running Auth database script...';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_strong_password123! -C -d master -i /scripts/create_login_database.sql;
        echo 'Running Manager database script...';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_strong_password123! -C -d master -i /scripts/create_manager_database.sql;
        echo 'Database initialization completed successfully!';
        echo 'Verifying setup...';
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_strong_password123! -C -Q 'SELECT name FROM sys.databases WHERE name IN (''NiceDentistAuthDb'', ''NiceDentistManagerDb'')';
        echo 'Setup complete. You can now connect to the databases.';
      "
    restart: "no"

volumes:
  mssqldata:
