services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./db.env
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "${SQL_PORT:-1433}:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sqlserver
    profiles:
      - init
    env_file:
      - ./db.env
    volumes:
      - ./Scripts:/scripts:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        if [ -x /opt/mssql-tools/bin/sqlcmd ]; then SQLCMD=/opt/mssql-tools/bin/sqlcmd; else SQLCMD=/opt/mssql-tools18/bin/sqlcmd; fi;
        until "$SQLCMD" -S sqlserver -U sa -P "$SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null 2>/dev/null; do echo "Waiting for SQL Server..."; sleep 2; done;
        "$SQLCMD" -S sqlserver -U sa -P "$SA_PASSWORD" -d master -i /scripts/create_login_database.sql
    restart: "no"

volumes:
  mssqldata:
